import { graphql } from 'gatsby';
import PropTypes from 'prop-types';
import React from 'react';
import Img from 'gatsby-image';
import Layout from '../components/layout';
import SEO from '../components/seo';
import Annotation from '../components/annotation';

export default function AboutUsTemplate({ pageContext, data }) {
  const { parentPage } = data;
  const [firstParagraph, ...otherParagraphs] = pageContext.text.split('\n');
  return (
    <Layout
      title={pageContext.name}
      navHomePath={pageContext.parentPath}
      render={({ isAnnotationsToggled }) => (
        <>
          <SEO title={pageContext.name} description={pageContext.title} />
          <div className="section">
            <div className="columns">
              <div className="column">
                <div className="section">
                  <h1 className="title">{pageContext.title}</h1>
                  <div className="is-flex is-justify-content-center">
                    <Annotation placement="bottom" isActive={isAnnotationsToggled}>
                      <strong>
                        About Us title indicates the origins of the storefront in the first "LOCATION" entity from Google Analysis.
                      </strong>
                    </Annotation>
                  </div>
                </div>
              </div>
              <div className="column is-5-desktop is-flex is-align-items-center is-justify-content-center">
                <div className="image">
                  <Img
                    fixed={parentPage.image.childImageSharp.fixed}
                    alt={parentPage.context.imageAlt}
                  />
                  <div className="is-flex is-justify-content-center">
                    <Annotation placement="bottom" isActive={isAnnotationsToggled}>
                      <strong>
                        About Us image is generated by Deep AI based on the above title prompt.
                      </strong>
                    </Annotation>
                  </div>
                </div>
              </div>
            </div>
            <div className="section">
              <p className="block">{firstParagraph}</p>
              <div className="is-flex is-justify-content-center">
                <Annotation placement="bottom" isActive={isAnnotationsToggled}>
                  <strong>
                    About Us description is generated by Deep AI based on the above title prompt.
                  </strong>
                </Annotation>
              </div>
              {otherParagraphs.map((paragraph) => (
                <p className="block">
                  {paragraph}
                </p>
              ))}
            </div>
          </div>
        </>
      )}
    />
  );
}

AboutUsTemplate.propTypes = {
  data: PropTypes.object.isRequired, // eslint-disable-line react/forbid-prop-types
};

export const pageQuery = graphql`
  query($parentPath: String!) {
    parentPage: sitePage(context: {pagePath: {eq: $parentPath}}) {
      context {
        imageAlt
      }
      image {
        childImageSharp {
          fixed(width: 250) {
            ...GatsbyImageSharpFixed
          }
        }
      }
    }
  }
`;
